services:
  python:
    build: .
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql